image: maven:3.8.1-jdk-11-openj9

stages:
  - build
  - test
  - check

ter-build:
    stage: build
    script:
        - mvn compile
    artifacts:
        paths:
            - target/

test-job:
  stage: test
  script:
    - mvn test -DskipTests=true -DlastModGranularityMs=10000000 
  artifacts:
    paths:
      - target/test-classes 
    expire_in: 1 hour 

check-job:
  stage: check
  script:
    - mvn sonar:sonar -DskipTests -DlastModGranularityMs=10000000
  only:
    - master
